# docker-compose.yml
version: '3'
services:
  web:
    build: .
    ports:
      - "${PORT}:5000"
    environment:
      - BASE_URL=${BASE_URL}
      - FLAG=${FLAG}
    volumes:
      - .:/app
      - /tmp:/tmp
